<div class="contestio-main-container error-page">
  <img
    src="<?php echo $block->getViewFileUrl('Contestio_Connect::images/error401.svg'); ?>"
    alt="Unauthorized"
    height="300"
    width="300"
  />

  <h3>
     Erreur d'authentification
  </h3>

  <p>
    Veuillez vérifier vos clés et réessayer.
  </p>

  <a
    href="https://contestio.fr/report-bug/?url=<?php echo $this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]); ?>&code=AUTH_401"
    target="_blank"
  >
    Signaler l'erreur
  </a>

  <?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Contestio_Connect::footer.phtml")->toHtml() ?>
</div>
