<?php
// Init variables
$user_pseudo = null;
$datas = [];
$pageUrl = null;

try {
	// Get from url (GET)
	$user_pseudo = $this->getRequest()->getParam('user');

	if (!$user_pseudo || empty($user_pseudo)) {
		throw new Exception('Peuso not found');
	}

	$datas = $block->fetchParticipationByPseudo($user_pseudo);

	if (isset($datas['code'])) {
		if ($datas['code'] == 'AUTH_401') {
			throw new Exception('Unauthorized');
		}
		throw new Exception('Participation not found');
	} else if (!$datas || !is_array($datas) || empty($datas)) {
		throw new Exception('Participation not found');
	}
	
	echo '<pre>';
	print_r($datas);
	echo '</pre>';

	// Get the URL of the current page
	$pageUrl = $this->getUrl('contestio/concours/?user=' . $user_pseudo, ['_secure' => true]);
} catch (Exception $e) {
	return null;
}
?>

<?php if (isset($datas['pseudo'])): ?>
	<meta property="og:title" content="@<?= htmlspecialchars($datas['pseudo'], ENT_QUOTES, 'UTF-8') ?>" />
	<meta name="twitter:title" content="@<?= htmlspecialchars($datas['pseudo'], ENT_QUOTES, 'UTF-8') ?>" />

	<!-- Meta description: Voter pour $pseudo -->
	<meta property="og:description" content="Voter pour <?= htmlspecialchars($datas['pseudo'], ENT_QUOTES, 'UTF-8') ?>" />
	<meta name="twitter:description" content="Voter pour <?= htmlspecialchars($datas['pseudo'], ENT_QUOTES, 'UTF-8') ?>" />
<?php endif; ?>

<!-- Site name : Voir les participation du concours. -->
<?php if (isset($datas['contestName'])): ?>
	<meta property="og:site_name" content="Voir les participations du concours : <?= htmlspecialchars($datas['contestName'], ENT_QUOTES, 'UTF-8') ?>" />
	<meta name="twitter:site" content="Voir les participations du concours : <?= htmlspecialchars($datas['contestName'], ENT_QUOTES, 'UTF-8') ?>" />
<?php endif; ?>

<?php if (isset($datas['presignedUrl'])): ?>
	<meta property="og:image" content="<?= htmlspecialchars($datas['presignedUrl'], ENT_QUOTES, 'UTF-8') ?>" />
	<meta name="twitter:image" content="<?= htmlspecialchars($datas['presignedUrl'], ENT_QUOTES, 'UTF-8') ?>" />
<?php endif; ?>

<?php if ($pageUrl): ?>
	<meta property="og:url" content="<?= htmlspecialchars($pageUrl, ENT_QUOTES, 'UTF-8') ?>" />
<?php endif; ?>

<meta property="og:type" content="article" />
<meta name="twitter:card" content="summary" />
