<?php
// Init variables
$participationid = null;
$contestData = [];
$participant = [];
$pageUrl = null;

try {
	$participationid = $block->getData('participationid');

	if (!$participationid || empty($participationid)) {
		throw new Exception('Not found');
	}

	$contestData = $block->fetchParticipationById($participationid);

	if (isset($contestData['code'])) {
		if ($contestData['code'] == 'AUTH_401') {
			throw new Exception('Unauthorized');
		}
	} else if (!$contestData) {
		throw new Exception('Not found');
	} if (isset($contestData['participation']) && !empty($contestData['participation'])) {
		$participant = $contestData['participation'];
	}

	// Get the URL of the current page
	$pageUrl = $this->getUrl('contestio/concours/index/partid/'.$participationid.'');
} catch (Exception $e) {
	return null;
}
?>

<?php if (isset($participant['handler'])): ?>
	<meta property="og:title" content="@<?= htmlspecialchars($participant['handler'], ENT_QUOTES, 'UTF-8') ?>" />
	<meta name="twitter:title" content="@<?= htmlspecialchars($participant['handler'], ENT_QUOTES, 'UTF-8') ?>" />
<?php elseif (isset($contestData['title'])): ?>
	<meta property="og:title" content="<?= htmlspecialchars($contestData['title'], ENT_QUOTES, 'UTF-8') ?>" />
	<meta name="twitter:title" content="<?= htmlspecialchars($contestData['title'], ENT_QUOTES, 'UTF-8') ?>" />

	<!-- Meta description: Voter pour $hanlde -->
	<meta property="og:description" content="Voter pour <?= htmlspecialchars($participant['handler'], ENT_QUOTES, 'UTF-8') ?>" />
	<meta name="twitter:description" content="Voter pour <?= htmlspecialchars($participant['handler'], ENT_QUOTES, 'UTF-8') ?>" />

	<!-- Site name : Voter pour $handle -->
	<meta property="og:site_name" content="Voter pour <?= htmlspecialchars($participant['handler'], ENT_QUOTES, 'UTF-8') ?>" />
<?php endif; ?>

<?php if (isset($participant['presignedUrl'])): ?>
	<meta property="og:image" content="<?= htmlspecialchars($participant['presignedUrl'], ENT_QUOTES, 'UTF-8') ?>" />
	<meta name="twitter:image" content="<?= htmlspecialchars($participant['presignedUrl'], ENT_QUOTES, 'UTF-8') ?>" />
<?php endif; ?>

<?php if ($pageUrl): ?>
	<meta property="og:url" content="<?= htmlspecialchars($pageUrl, ENT_QUOTES, 'UTF-8') ?>" />
<?php endif; ?>

<meta property="og:type" content="article" />
<meta name="twitter:card" content="summary" />